runtime: python39
entrypoint: uvicorn app.main:app --host 0.0.0.0 --port $PORT

env_variables:
  SECRET_KEY: "change-this-to-a-secure-random-key-in-production"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "10080"

  # --- Cloud SQL (PostgreSQL) ---
  DB_DIALECT: "postgresql+pg8000"
  DB_INSTANCE: "qtsisa:us-central1:isa-postgres"
  DB_NAME: "isa_db"
  DB_USER: "isa_user"
  DB_PASS: "admin123"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0       # <— para gastar menos en idle
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

instance_class: F2
