runtime: nodejs20
env: standard

handlers:
  - url: /_next/static
    static_dir: .next/static
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt|svg|webp))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|ico|txt|svg|webp)$
    secure: always

  - url: /.*
    script: auto
    secure: always

env_variables:
  NEXT_PUBLIC_API_URL: "https://your-backend-url.appspot.com"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

instance_class: F2
